import os

ROOT_AGENT_MODEL = os.getenv("ROOT_AGENT_MODEL")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION")


BQ_DATA_PROJECT_ID = os.getenv("BQ_DATA_PROJECT_ID")

BQ_DATASET_ID = os.getenv("BQ_FINOPS_DATASET_ID")
BQ_TABLE_ID = os.getenv("BQ_DATA_BQ_TABLE_IDPROJECT_ID")
ACME_DATASTORE_ID = os.getenv("ACME_DATASTORE_ID","")
ROOT_AGENT_MODEL = os.getenv("ROOT_AGENT_MODEL","")
