import os

PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT")
GCS_DEFAULT_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION")
GCS_LIST_BUCKETS_MAX_RESULTS = 100
GCS_LIST_BLOBS_MAX_RESULTS = 100
GCS_DEFAULT_STORAGE_CLASS = "STANDARD"
GCS_DEFAULT_CONTENT_TYPE = "text/plain"
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s %(clientip)-15s %(user)-8s %(message)s"
