PROJECT_ID='ai-agent-bar-2026-stage'
GCS_LIST_BUCKETS_MAX_RESULTS = 100
GCS_LIST_BLOBS_MAX_RESULTS = 100
GCS_DEFAULT_STORAGE_CLASS='STANDARD'
GCS_DEFAULT_LOCATION='us-central1'
GCS_DEFAULT_CONTENT_TYPE = 'text/plain'
LOG_LEVEL='INFO'
LOG_FORMAT = '%(asctime)s %(clientip)-15s %(user)-8s %(message)s'