import os

GCP_PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT")
GCP_DATASET_ID = os.getenv("GCP_DATASET_ID")
GCP_PRODUCT_TABLE_ID = os.getenv("GCP_PRODUCT_TABLE_ID")
GCP_STORE_TABLE_ID = os.getenv("GCP_STORE_TABLE_ID")
GCP_INVENTORY_TABLE_ID = os.getenv("GCP_INVENTORY_TABLE_ID")
