# Copyright 2026 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Synthetic provider directory dataset for the Greater Houston, TX and
Greater Chicago, IL metro areas.

Contains organizations, facilities, and practitioners with realistic
attributes, geographic coordinates, and inter-entity relationships.
"""

ORGANIZATIONS = [
    {
        "id": "ORG001",
        "npi": "1000000001",
        "name": "Memorial Hermann Health System",
        "type": "hospital_system",
        "address": {
            "street": "929 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
        "phone": "(713) 222-2273",
        "website": "https://memorialhermann.org",
    },
    {
        "id": "ORG002",
        "npi": "1000000002",
        "name": "Houston Methodist",
        "type": "hospital_system",
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
        "phone": "(713) 790-3311",
        "website": "https://houstonmethodist.org",
    },
    {
        "id": "ORG003",
        "npi": "1000000003",
        "name": "Lone Star Medical Group",
        "type": "medical_group",
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
        "phone": "(713) 555-0103",
        "website": "https://lonestarmg.example.com",
    },
    {
        "id": "ORG004",
        "npi": "1000000004",
        "name": "Bayou City Primary Care",
        "type": "medical_group",
        "address": {
            "street": "1200 Binz St",
            "city": "Houston",
            "state": "TX",
            "zip": "77004",
            "latitude": 29.7260,
            "longitude": -95.3886,
        },
        "phone": "(713) 555-0104",
        "website": "https://bayoucityprimarycare.example.com",
    },
    {
        "id": "ORG005",
        "npi": "1000000005",
        "name": "Gulf Coast Community Health",
        "type": "community_health_center",
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
        "phone": "(713) 555-0105",
        "website": "https://gulfcoasthealth.example.com",
    },
    {
        "id": "ORG006",
        "npi": "1000000006",
        "name": "Texas Pediatric Associates",
        "type": "specialty_group",
        "address": {
            "street": "6624 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7086,
            "longitude": -95.3978,
        },
        "phone": "(713) 555-0106",
        "website": "https://texaspediatric.example.com",
    },
    {
        "id": "ORG007",
        "npi": "1000000007",
        "name": "Magnolia Women's Health",
        "type": "specialty_group",
        "address": {
            "street": "1415 Louisiana St",
            "city": "Houston",
            "state": "TX",
            "zip": "77002",
            "latitude": 29.7520,
            "longitude": -95.3660,
        },
        "phone": "(713) 555-0107",
        "website": "https://magnoliawomens.example.com",
    },
    {
        "id": "ORG008",
        "npi": "1000000008",
        "name": "Cypress Creek Medical Partners",
        "type": "medical_group",
        "address": {
            "street": "21216 Northwest Fwy",
            "city": "Cypress",
            "state": "TX",
            "zip": "77429",
            "latitude": 29.9630,
            "longitude": -95.6700,
        },
        "phone": "(281) 555-0108",
        "website": "https://cypresscreekmed.example.com",
    },
    # --- Chicago metro organizations ---
    {
        "id": "ORG009",
        "npi": "1000000009",
        "name": "Mercy Hospital & Medical Center",
        "type": "hospital_system",
        "address": {
            "street": "2525 S Michigan Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8462,
            "longitude": -87.6228,
        },
        "phone": "(312) 567-2000",
        "website": "https://mercy-chicago.example.com",
    },
    {
        "id": "ORG010",
        "npi": "1000000010",
        "name": "Lakeshore Behavioral Health",
        "type": "specialty_group",
        "address": {
            "street": "2650 N Lakeview Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60614",
            "latitude": 41.9310,
            "longitude": -87.6440,
        },
        "phone": "(773) 555-0110",
        "website": "https://lakeshorebehavioral.example.com",
    },
    {
        "id": "ORG011",
        "npi": "1000000011",
        "name": "North Side Community Health",
        "type": "community_health_center",
        "address": {
            "street": "3059 W Diversey Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9322,
            "longitude": -87.7052,
        },
        "phone": "(773) 555-0111",
        "website": "https://northsidecommunity.example.com",
    },
]

FACILITIES = [
    {
        "id": "FAC001",
        "npi": "1100000001",
        "name": "Memorial Hermann Memorial City Medical Center",
        "type": "hospital",
        "organization_id": "ORG001",
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
        "phone": "(713) 242-2000",
        "services": [
            "emergency",
            "cardiology",
            "orthopedics",
            "neurology",
            "oncology",
            "maternity",
            "imaging",
            "laboratory",
        ],
        "hours": "24/7",
    },
    {
        "id": "FAC002",
        "npi": "1100000002",
        "name": "Memorial Hermann The Woodlands Medical Center",
        "type": "hospital",
        "organization_id": "ORG001",
        "address": {
            "street": "9250 Pinecroft Dr",
            "city": "The Woodlands",
            "state": "TX",
            "zip": "77380",
            "latitude": 30.1658,
            "longitude": -95.4613,
        },
        "phone": "(713) 897-2000",
        "services": [
            "emergency",
            "cardiology",
            "orthopedics",
            "maternity",
            "imaging",
            "laboratory",
            "rehabilitation",
        ],
        "hours": "24/7",
    },
    {
        "id": "FAC003",
        "npi": "1100000003",
        "name": "Houston Methodist Hospital",
        "type": "hospital",
        "organization_id": "ORG002",
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
        "phone": "(713) 790-3311",
        "services": [
            "emergency",
            "cardiology",
            "orthopedics",
            "neurology",
            "oncology",
            "transplant",
            "imaging",
            "laboratory",
            "rehabilitation",
        ],
        "hours": "24/7",
    },
    {
        "id": "FAC004",
        "npi": "1100000004",
        "name": "Houston Methodist Baytown Hospital",
        "type": "hospital",
        "organization_id": "ORG002",
        "address": {
            "street": "4401 Garth Rd",
            "city": "Baytown",
            "state": "TX",
            "zip": "77521",
            "latitude": 29.7355,
            "longitude": -94.9774,
        },
        "phone": "(281) 420-8600",
        "services": [
            "emergency",
            "cardiology",
            "orthopedics",
            "imaging",
            "laboratory",
        ],
        "hours": "24/7",
    },
    {
        "id": "FAC005",
        "npi": "1100000005",
        "name": "Lone Star Medical Clinic – Montrose",
        "type": "clinic",
        "organization_id": "ORG003",
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
        "phone": "(713) 555-0205",
        "services": [
            "primary_care",
            "internal_medicine",
            "dermatology",
            "laboratory",
        ],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-1pm",
    },
    {
        "id": "FAC006",
        "npi": "1100000006",
        "name": "Lone Star Medical Clinic – Katy",
        "type": "clinic",
        "organization_id": "ORG003",
        "address": {
            "street": "1463 S Mason Rd",
            "city": "Katy",
            "state": "TX",
            "zip": "77450",
            "latitude": 29.7558,
            "longitude": -95.7697,
        },
        "phone": "(281) 555-0206",
        "services": [
            "primary_care",
            "internal_medicine",
            "pediatrics",
            "laboratory",
        ],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-1pm",
    },
    {
        "id": "FAC007",
        "npi": "1100000007",
        "name": "Bayou City Primary Care – Downtown",
        "type": "clinic",
        "organization_id": "ORG004",
        "address": {
            "street": "1200 Binz St",
            "city": "Houston",
            "state": "TX",
            "zip": "77004",
            "latitude": 29.7260,
            "longitude": -95.3886,
        },
        "phone": "(713) 555-0207",
        "services": ["primary_care", "family_medicine", "preventive_care", "laboratory"],
        "hours": "Mon-Fri 7am-7pm, Sat 8am-2pm",
    },
    {
        "id": "FAC008",
        "npi": "1100000008",
        "name": "Bayou City Primary Care – Sugar Land",
        "type": "clinic",
        "organization_id": "ORG004",
        "address": {
            "street": "16659 Southwest Fwy",
            "city": "Sugar Land",
            "state": "TX",
            "zip": "77479",
            "latitude": 29.6197,
            "longitude": -95.6349,
        },
        "phone": "(281) 555-0208",
        "services": ["primary_care", "family_medicine", "preventive_care"],
        "hours": "Mon-Fri 8am-5pm",
    },
    {
        "id": "FAC009",
        "npi": "1100000009",
        "name": "Gulf Coast Community Health Center – Hillcroft",
        "type": "community_health_center",
        "organization_id": "ORG005",
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
        "phone": "(713) 555-0209",
        "services": [
            "primary_care",
            "family_medicine",
            "pediatrics",
            "dental",
            "behavioral_health",
            "laboratory",
        ],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-12pm",
    },
    {
        "id": "FAC010",
        "npi": "1100000010",
        "name": "Gulf Coast Community Health Center – Pasadena",
        "type": "community_health_center",
        "organization_id": "ORG005",
        "address": {
            "street": "3737 Red Bluff Rd",
            "city": "Pasadena",
            "state": "TX",
            "zip": "77503",
            "latitude": 29.6911,
            "longitude": -95.2091,
        },
        "phone": "(713) 555-0210",
        "services": [
            "primary_care",
            "family_medicine",
            "pediatrics",
            "dental",
            "behavioral_health",
        ],
        "hours": "Mon-Fri 8am-5pm",
    },
    {
        "id": "FAC011",
        "npi": "1100000011",
        "name": "Texas Pediatric Associates – Medical Center",
        "type": "pediatric_clinic",
        "organization_id": "ORG006",
        "address": {
            "street": "6624 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7086,
            "longitude": -95.3978,
        },
        "phone": "(713) 555-0211",
        "services": [
            "pediatrics",
            "pediatric_cardiology",
            "pediatric_neurology",
            "immunizations",
        ],
        "hours": "Mon-Fri 8am-5pm, Sat 9am-12pm",
    },
    {
        "id": "FAC012",
        "npi": "1100000012",
        "name": "Magnolia Women's Health – Downtown",
        "type": "womens_health_clinic",
        "organization_id": "ORG007",
        "address": {
            "street": "1415 Louisiana St",
            "city": "Houston",
            "state": "TX",
            "zip": "77002",
            "latitude": 29.7520,
            "longitude": -95.3660,
        },
        "phone": "(713) 555-0212",
        "services": ["obstetrics", "gynecology", "reproductive_health", "imaging"],
        "hours": "Mon-Fri 8am-5pm",
    },
    {
        "id": "FAC013",
        "npi": "1100000013",
        "name": "Magnolia Women's Health – Pearland",
        "type": "womens_health_clinic",
        "organization_id": "ORG007",
        "address": {
            "street": "2950 Cullen Blvd",
            "city": "Pearland",
            "state": "TX",
            "zip": "77584",
            "latitude": 29.5636,
            "longitude": -95.2860,
        },
        "phone": "(281) 555-0213",
        "services": ["obstetrics", "gynecology", "reproductive_health"],
        "hours": "Mon-Fri 8am-5pm",
    },
    {
        "id": "FAC014",
        "npi": "1100000014",
        "name": "Cypress Creek Family Medicine",
        "type": "clinic",
        "organization_id": "ORG008",
        "address": {
            "street": "21216 Northwest Fwy",
            "city": "Cypress",
            "state": "TX",
            "zip": "77429",
            "latitude": 29.9630,
            "longitude": -95.6700,
        },
        "phone": "(281) 555-0214",
        "services": ["primary_care", "family_medicine", "preventive_care", "laboratory"],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-1pm",
    },
    {
        "id": "FAC015",
        "npi": "1100000015",
        "name": "Memorial Hermann Urgent Care – Meyerland",
        "type": "urgent_care",
        "organization_id": "ORG001",
        "address": {
            "street": "4700 Beechnut St",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6875,
            "longitude": -95.4622,
        },
        "phone": "(713) 555-0215",
        "services": ["urgent_care", "x_ray", "laboratory", "vaccinations"],
        "hours": "Mon-Sun 8am-8pm",
    },
    # --- Chicago metro facilities ---
    {
        "id": "FAC016",
        "npi": "1100000016",
        "name": "Mercy Hospital & Medical Center",
        "type": "hospital",
        "organization_id": "ORG009",
        "address": {
            "street": "2525 S Michigan Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8462,
            "longitude": -87.6228,
        },
        "phone": "(312) 567-2000",
        "services": [
            "emergency",
            "cardiology",
            "orthopedics",
            "oncology",
            "maternity",
            "imaging",
            "laboratory",
            "pharmacy",
            "behavioral_health",
        ],
        "hours": "24/7",
    },
    {
        "id": "FAC017",
        "npi": "1100000017",
        "name": "Mercy Family Health Center – Bronzeville",
        "type": "clinic",
        "organization_id": "ORG009",
        "address": {
            "street": "2640 S King Dr",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8445,
            "longitude": -87.6170,
        },
        "phone": "(312) 567-2100",
        "services": ["primary_care", "family_medicine", "pediatrics", "pharmacy", "laboratory"],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-1pm",
    },
    {
        "id": "FAC018",
        "npi": "1100000018",
        "name": "Museum Campus Pharmacy",
        "type": "pharmacy",
        "organization_id": None,
        "address": {
            "street": "1301 S Lake Shore Dr",
            "city": "Chicago",
            "state": "IL",
            "zip": "60605",
            "latitude": 41.8680,
            "longitude": -87.6169,
        },
        "phone": "(312) 555-0218",
        "services": ["pharmacy", "prescriptions", "vaccinations", "otc_medications"],
        "hours": "Mon-Fri 8am-9pm, Sat 9am-6pm, Sun 10am-5pm",
    },
    {
        "id": "FAC019",
        "npi": "1100000019",
        "name": "South Loop Pharmacy & Wellness",
        "type": "pharmacy",
        "organization_id": None,
        "address": {
            "street": "47 W Polk St",
            "city": "Chicago",
            "state": "IL",
            "zip": "60605",
            "latitude": 41.8718,
            "longitude": -87.6291,
        },
        "phone": "(312) 555-0219",
        "services": ["pharmacy", "prescriptions", "vaccinations", "compounding", "otc_medications"],
        "hours": "Mon-Fri 8am-8pm, Sat 9am-5pm",
    },
    {
        "id": "FAC020",
        "npi": "1100000020",
        "name": "Prairie Avenue Pharmacy",
        "type": "pharmacy",
        "organization_id": None,
        "address": {
            "street": "2100 S Prairie Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8543,
            "longitude": -87.6198,
        },
        "phone": "(312) 555-0220",
        "services": ["pharmacy", "prescriptions", "vaccinations", "delivery"],
        "hours": "Mon-Sat 9am-7pm",
    },
    {
        "id": "FAC021",
        "npi": "1100000021",
        "name": "Logan Square Behavioral Health Center",
        "type": "behavioral_health_clinic",
        "organization_id": "ORG010",
        "address": {
            "street": "2553 N Kedzie Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9270,
            "longitude": -87.7076,
        },
        "phone": "(773) 555-0221",
        "services": ["psychology", "psychiatry", "counseling", "behavioral_health", "group_therapy"],
        "hours": "Mon-Fri 8am-7pm, Sat 9am-3pm",
    },
    {
        "id": "FAC022",
        "npi": "1100000022",
        "name": "North Side Community Health – Logan Square",
        "type": "community_health_center",
        "organization_id": "ORG011",
        "address": {
            "street": "3059 W Diversey Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9322,
            "longitude": -87.7052,
        },
        "phone": "(773) 555-0222",
        "services": ["primary_care", "behavioral_health", "psychology", "pediatrics", "dental"],
        "hours": "Mon-Fri 8am-6pm, Sat 9am-12pm",
    },
    {
        "id": "FAC023",
        "npi": "1100000023",
        "name": "Bucktown-Wicker Park Pharmacy",
        "type": "pharmacy",
        "organization_id": None,
        "address": {
            "street": "1701 N Milwaukee Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9132,
            "longitude": -87.6738,
        },
        "phone": "(773) 555-0223",
        "services": ["pharmacy", "prescriptions", "vaccinations", "otc_medications"],
        "hours": "Mon-Fri 8am-9pm, Sat 9am-6pm, Sun 10am-5pm",
    },
]

PRACTITIONERS = [
    # --- Family Medicine / Primary Care ---
    {
        "npi": "1200000001",
        "first_name": "Sarah",
        "last_name": "Chen",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Mandarin"],
        "phone": "(713) 555-1001",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG004"],
        "facility_ids": ["FAC007"],
        "address": {
            "street": "1200 Binz St",
            "city": "Houston",
            "state": "TX",
            "zip": "77004",
            "latitude": 29.7260,
            "longitude": -95.3886,
        },
    },
    {
        "npi": "1200000002",
        "first_name": "Marcus",
        "last_name": "Williams",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": ["Sports Medicine"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(713) 555-1002",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG004"],
        "facility_ids": ["FAC007", "FAC008"],
        "address": {
            "street": "1200 Binz St",
            "city": "Houston",
            "state": "TX",
            "zip": "77004",
            "latitude": 29.7260,
            "longitude": -95.3886,
        },
    },
    {
        "npi": "1200000003",
        "first_name": "Priya",
        "last_name": "Patel",
        "prefix": "Dr.",
        "credentials": "DO",
        "specialty": "Family Medicine",
        "subspecialties": ["Geriatric Medicine"],
        "gender": "Female",
        "languages": ["English", "Hindi", "Gujarati"],
        "phone": "(281) 555-1003",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG004"],
        "facility_ids": ["FAC008"],
        "address": {
            "street": "16659 Southwest Fwy",
            "city": "Sugar Land",
            "state": "TX",
            "zip": "77479",
            "latitude": 29.6197,
            "longitude": -95.6349,
        },
    },
    {
        "npi": "1200000004",
        "first_name": "James",
        "last_name": "Okafor",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English", "Igbo"],
        "phone": "(281) 555-1004",
        "accepting_new_patients": False,
        "telehealth_available": True,
        "organization_ids": ["ORG008"],
        "facility_ids": ["FAC014"],
        "address": {
            "street": "21216 Northwest Fwy",
            "city": "Cypress",
            "state": "TX",
            "zip": "77429",
            "latitude": 29.9630,
            "longitude": -95.6700,
        },
    },
    # --- Internal Medicine ---
    {
        "npi": "1200000005",
        "first_name": "Elena",
        "last_name": "Rodriguez",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Internal Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Spanish"],
        "phone": "(713) 555-1005",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG003"],
        "facility_ids": ["FAC005"],
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
    },
    {
        "npi": "1200000006",
        "first_name": "David",
        "last_name": "Kim",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Internal Medicine",
        "subspecialties": ["Hospital Medicine"],
        "gender": "Male",
        "languages": ["English", "Korean"],
        "phone": "(713) 555-1006",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000007",
        "first_name": "Fatima",
        "last_name": "Al-Rashid",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Internal Medicine",
        "subspecialties": ["Infectious Disease"],
        "gender": "Female",
        "languages": ["English", "Arabic"],
        "phone": "(713) 555-1007",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG003"],
        "facility_ids": ["FAC005", "FAC006"],
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
    },
    # --- Cardiology ---
    {
        "npi": "1200000008",
        "first_name": "Robert",
        "last_name": "Tran",
        "prefix": "Dr.",
        "credentials": "MD, FACC",
        "specialty": "Cardiology",
        "subspecialties": ["Interventional Cardiology"],
        "gender": "Male",
        "languages": ["English", "Vietnamese"],
        "phone": "(713) 555-1008",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000009",
        "first_name": "Angela",
        "last_name": "Foster",
        "prefix": "Dr.",
        "credentials": "MD, FACC",
        "specialty": "Cardiology",
        "subspecialties": ["Electrophysiology"],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1009",
        "accepting_new_patients": False,
        "telehealth_available": True,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    {
        "npi": "1200000010",
        "first_name": "Alejandro",
        "last_name": "Gutierrez",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Cardiology",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English", "Spanish"],
        "phone": "(713) 555-1010",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001", "FAC002"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    # --- Orthopedics ---
    {
        "npi": "1200000011",
        "first_name": "Michael",
        "last_name": "Thompson",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Orthopedic Surgery",
        "subspecialties": ["Joint Replacement"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(713) 555-1011",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000012",
        "first_name": "Lisa",
        "last_name": "Nakamura",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Orthopedic Surgery",
        "subspecialties": ["Sports Medicine", "Shoulder & Elbow"],
        "gender": "Female",
        "languages": ["English", "Japanese"],
        "phone": "(713) 555-1012",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001", "FAC002"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    # --- Pediatrics ---
    {
        "npi": "1200000013",
        "first_name": "Amara",
        "last_name": "Osei",
        "prefix": "Dr.",
        "credentials": "MD, FAAP",
        "specialty": "Pediatrics",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Twi"],
        "phone": "(713) 555-1013",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG006"],
        "facility_ids": ["FAC011"],
        "address": {
            "street": "6624 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7086,
            "longitude": -95.3978,
        },
    },
    {
        "npi": "1200000014",
        "first_name": "Carlos",
        "last_name": "Mendez",
        "prefix": "Dr.",
        "credentials": "MD, FAAP",
        "specialty": "Pediatrics",
        "subspecialties": ["Pediatric Cardiology"],
        "gender": "Male",
        "languages": ["English", "Spanish"],
        "phone": "(713) 555-1014",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG006"],
        "facility_ids": ["FAC011"],
        "address": {
            "street": "6624 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7086,
            "longitude": -95.3978,
        },
    },
    {
        "npi": "1200000015",
        "first_name": "Rachel",
        "last_name": "Goldstein",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Pediatrics",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Hebrew"],
        "phone": "(713) 555-1015",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG005"],
        "facility_ids": ["FAC009"],
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
    },
    # --- OB/GYN ---
    {
        "npi": "1200000016",
        "first_name": "Jennifer",
        "last_name": "Brooks",
        "prefix": "Dr.",
        "credentials": "MD, FACOG",
        "specialty": "Obstetrics & Gynecology",
        "subspecialties": ["Maternal-Fetal Medicine"],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1016",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG007"],
        "facility_ids": ["FAC012"],
        "address": {
            "street": "1415 Louisiana St",
            "city": "Houston",
            "state": "TX",
            "zip": "77002",
            "latitude": 29.7520,
            "longitude": -95.3660,
        },
    },
    {
        "npi": "1200000017",
        "first_name": "Nadia",
        "last_name": "Hassan",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Obstetrics & Gynecology",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Arabic", "French"],
        "phone": "(281) 555-1017",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG007"],
        "facility_ids": ["FAC013"],
        "address": {
            "street": "2950 Cullen Blvd",
            "city": "Pearland",
            "state": "TX",
            "zip": "77584",
            "latitude": 29.5636,
            "longitude": -95.2860,
        },
    },
    {
        "npi": "1200000018",
        "first_name": "Stephanie",
        "last_name": "Nguyen",
        "prefix": "Dr.",
        "credentials": "MD, FACOG",
        "specialty": "Obstetrics & Gynecology",
        "subspecialties": ["Reproductive Endocrinology"],
        "gender": "Female",
        "languages": ["English", "Vietnamese"],
        "phone": "(713) 555-1018",
        "accepting_new_patients": False,
        "telehealth_available": True,
        "organization_ids": ["ORG007"],
        "facility_ids": ["FAC012"],
        "address": {
            "street": "1415 Louisiana St",
            "city": "Houston",
            "state": "TX",
            "zip": "77002",
            "latitude": 29.7520,
            "longitude": -95.3660,
        },
    },
    # --- Dermatology ---
    {
        "npi": "1200000019",
        "first_name": "Kevin",
        "last_name": "Park",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Dermatology",
        "subspecialties": ["Cosmetic Dermatology"],
        "gender": "Male",
        "languages": ["English", "Korean"],
        "phone": "(713) 555-1019",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG003"],
        "facility_ids": ["FAC005"],
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
    },
    {
        "npi": "1200000020",
        "first_name": "Maria",
        "last_name": "Santos",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Dermatology",
        "subspecialties": ["Mohs Surgery"],
        "gender": "Female",
        "languages": ["English", "Spanish", "Portuguese"],
        "phone": "(713) 555-1020",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG003"],
        "facility_ids": ["FAC005", "FAC006"],
        "address": {
            "street": "2727 Allen Pkwy",
            "city": "Houston",
            "state": "TX",
            "zip": "77019",
            "latitude": 29.7604,
            "longitude": -95.3926,
        },
    },
    # --- Psychiatry ---
    {
        "npi": "1200000021",
        "first_name": "Daniel",
        "last_name": "Washington",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Psychiatry",
        "subspecialties": ["Addiction Psychiatry"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(713) 555-1021",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG005"],
        "facility_ids": ["FAC009"],
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
    },
    {
        "npi": "1200000022",
        "first_name": "Yuki",
        "last_name": "Tanaka",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Psychiatry",
        "subspecialties": ["Child & Adolescent Psychiatry"],
        "gender": "Female",
        "languages": ["English", "Japanese"],
        "phone": "(713) 555-1022",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG005"],
        "facility_ids": ["FAC009", "FAC010"],
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
    },
    # --- Neurology ---
    {
        "npi": "1200000023",
        "first_name": "Omar",
        "last_name": "Farah",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Neurology",
        "subspecialties": ["Stroke & Cerebrovascular"],
        "gender": "Male",
        "languages": ["English", "Somali", "Arabic"],
        "phone": "(713) 555-1023",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000024",
        "first_name": "Catherine",
        "last_name": "Liu",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Neurology",
        "subspecialties": ["Epilepsy"],
        "gender": "Female",
        "languages": ["English", "Mandarin"],
        "phone": "(713) 555-1024",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    # --- Endocrinology ---
    {
        "npi": "1200000025",
        "first_name": "Anil",
        "last_name": "Sharma",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Endocrinology",
        "subspecialties": ["Diabetes Management"],
        "gender": "Male",
        "languages": ["English", "Hindi"],
        "phone": "(713) 555-1025",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    # --- Oncology ---
    {
        "npi": "1200000026",
        "first_name": "Grace",
        "last_name": "Abernathy",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Oncology",
        "subspecialties": ["Breast Oncology"],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1026",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000027",
        "first_name": "Victor",
        "last_name": "Okonkwo",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Oncology",
        "subspecialties": ["Hematologic Oncology"],
        "gender": "Male",
        "languages": ["English", "Igbo"],
        "phone": "(713) 555-1027",
        "accepting_new_patients": False,
        "telehealth_available": True,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001", "FAC002"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    # --- Pulmonology ---
    {
        "npi": "1200000028",
        "first_name": "Rita",
        "last_name": "Vasquez",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Pulmonology",
        "subspecialties": ["Critical Care"],
        "gender": "Female",
        "languages": ["English", "Spanish"],
        "phone": "(713) 555-1028",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    # --- Gastroenterology ---
    {
        "npi": "1200000029",
        "first_name": "Ahmed",
        "last_name": "Khalil",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Gastroenterology",
        "subspecialties": ["Hepatology"],
        "gender": "Male",
        "languages": ["English", "Arabic"],
        "phone": "(713) 555-1029",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003", "FAC004"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    # --- Ophthalmology ---
    {
        "npi": "1200000030",
        "first_name": "Diane",
        "last_name": "Monroe",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Ophthalmology",
        "subspecialties": ["Retina & Vitreous"],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1030",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    # --- Additional Primary Care (distributed across suburbs) ---
    {
        "npi": "1200000031",
        "first_name": "Laura",
        "last_name": "Martinez",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Spanish"],
        "phone": "(281) 555-1031",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG005"],
        "facility_ids": ["FAC010"],
        "address": {
            "street": "3737 Red Bluff Rd",
            "city": "Pasadena",
            "state": "TX",
            "zip": "77503",
            "latitude": 29.6911,
            "longitude": -95.2091,
        },
    },
    {
        "npi": "1200000032",
        "first_name": "Brian",
        "last_name": "Sullivan",
        "prefix": "Dr.",
        "credentials": "DO",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(281) 555-1032",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG008"],
        "facility_ids": ["FAC014"],
        "address": {
            "street": "21216 Northwest Fwy",
            "city": "Cypress",
            "state": "TX",
            "zip": "77429",
            "latitude": 29.9630,
            "longitude": -95.6700,
        },
    },
    {
        "npi": "1200000033",
        "first_name": "Mei",
        "last_name": "Zhang",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Internal Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Mandarin", "Cantonese"],
        "phone": "(281) 555-1033",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG003"],
        "facility_ids": ["FAC006"],
        "address": {
            "street": "1463 S Mason Rd",
            "city": "Katy",
            "state": "TX",
            "zip": "77450",
            "latitude": 29.7558,
            "longitude": -95.7697,
        },
    },
    # --- Nurse Practitioners & PAs ---
    {
        "npi": "1200000034",
        "first_name": "Tamika",
        "last_name": "Reynolds",
        "prefix": "",
        "credentials": "NP",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1034",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG005"],
        "facility_ids": ["FAC009"],
        "address": {
            "street": "8501 Hillcroft Ave",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6930,
            "longitude": -95.5126,
        },
    },
    {
        "npi": "1200000035",
        "first_name": "Jason",
        "last_name": "Cooper",
        "prefix": "",
        "credentials": "PA-C",
        "specialty": "Orthopedic Surgery",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English", "Spanish"],
        "phone": "(713) 555-1035",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC003"],
        "address": {
            "street": "6565 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7096,
            "longitude": -95.3984,
        },
    },
    {
        "npi": "1200000036",
        "first_name": "Sophia",
        "last_name": "Petrov",
        "prefix": "",
        "credentials": "NP",
        "specialty": "Pediatrics",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Russian"],
        "phone": "(713) 555-1036",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG006"],
        "facility_ids": ["FAC011"],
        "address": {
            "street": "6624 Fannin St",
            "city": "Houston",
            "state": "TX",
            "zip": "77030",
            "latitude": 29.7086,
            "longitude": -95.3978,
        },
    },
    # --- Emergency Medicine ---
    {
        "npi": "1200000037",
        "first_name": "Derek",
        "last_name": "Ingram",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Emergency Medicine",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(713) 555-1037",
        "accepting_new_patients": False,
        "telehealth_available": False,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC001", "FAC015"],
        "address": {
            "street": "921 Gessner Rd",
            "city": "Houston",
            "state": "TX",
            "zip": "77024",
            "latitude": 29.7804,
            "longitude": -95.5546,
        },
    },
    {
        "npi": "1200000038",
        "first_name": "Rosa",
        "last_name": "Delgado",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Emergency Medicine",
        "subspecialties": ["Pediatric Emergency Medicine"],
        "gender": "Female",
        "languages": ["English", "Spanish"],
        "phone": "(281) 555-1038",
        "accepting_new_patients": False,
        "telehealth_available": False,
        "organization_ids": ["ORG002"],
        "facility_ids": ["FAC004"],
        "address": {
            "street": "4401 Garth Rd",
            "city": "Baytown",
            "state": "TX",
            "zip": "77521",
            "latitude": 29.7355,
            "longitude": -94.9774,
        },
    },
    # --- Urgent Care ---
    {
        "npi": "1200000039",
        "first_name": "Anthony",
        "last_name": "Bell",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": ["Urgent Care"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(713) 555-1039",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC015"],
        "address": {
            "street": "4700 Beechnut St",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6875,
            "longitude": -95.4622,
        },
    },
    {
        "npi": "1200000040",
        "first_name": "Hannah",
        "last_name": "Mitchell",
        "prefix": "",
        "credentials": "NP",
        "specialty": "Family Medicine",
        "subspecialties": ["Urgent Care"],
        "gender": "Female",
        "languages": ["English"],
        "phone": "(713) 555-1040",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG001"],
        "facility_ids": ["FAC015"],
        "address": {
            "street": "4700 Beechnut St",
            "city": "Houston",
            "state": "TX",
            "zip": "77096",
            "latitude": 29.6875,
            "longitude": -95.4622,
        },
    },
    # --- Chicago metro: Psychologists (near Logan Square) ---
    {
        "npi": "1200000041",
        "first_name": "Isabel",
        "last_name": "Reyes",
        "prefix": "Dr.",
        "credentials": "PsyD",
        "specialty": "Psychology",
        "subspecialties": ["Cognitive Behavioral Therapy"],
        "gender": "Female",
        "languages": ["English", "Spanish"],
        "phone": "(773) 555-1041",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG010"],
        "facility_ids": ["FAC021"],
        "address": {
            "street": "2553 N Kedzie Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9270,
            "longitude": -87.7076,
        },
    },
    {
        "npi": "1200000042",
        "first_name": "Nathan",
        "last_name": "Byrne",
        "prefix": "Dr.",
        "credentials": "PhD",
        "specialty": "Psychology",
        "subspecialties": ["Clinical Neuropsychology"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(773) 555-1042",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG010"],
        "facility_ids": ["FAC021"],
        "address": {
            "street": "2553 N Kedzie Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9270,
            "longitude": -87.7076,
        },
    },
    {
        "npi": "1200000043",
        "first_name": "Anya",
        "last_name": "Kowalski",
        "prefix": "Dr.",
        "credentials": "PsyD",
        "specialty": "Psychology",
        "subspecialties": ["Child & Adolescent Psychology"],
        "gender": "Female",
        "languages": ["English", "Polish"],
        "phone": "(773) 555-1043",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG011"],
        "facility_ids": ["FAC022"],
        "address": {
            "street": "3059 W Diversey Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9322,
            "longitude": -87.7052,
        },
    },
    {
        "npi": "1200000044",
        "first_name": "Marcus",
        "last_name": "Grant",
        "prefix": "Dr.",
        "credentials": "PhD",
        "specialty": "Psychology",
        "subspecialties": ["Trauma & PTSD"],
        "gender": "Male",
        "languages": ["English"],
        "phone": "(773) 555-1044",
        "accepting_new_patients": False,
        "telehealth_available": True,
        "organization_ids": ["ORG010"],
        "facility_ids": ["FAC021"],
        "address": {
            "street": "2553 N Kedzie Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9270,
            "longitude": -87.7076,
        },
    },
    # --- Chicago metro: Mercy Hospital practitioners ---
    {
        "npi": "1200000045",
        "first_name": "Patricia",
        "last_name": "Doyle",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Internal Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Irish"],
        "phone": "(312) 555-1045",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG009"],
        "facility_ids": ["FAC016", "FAC017"],
        "address": {
            "street": "2525 S Michigan Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8462,
            "longitude": -87.6228,
        },
    },
    {
        "npi": "1200000046",
        "first_name": "Samuel",
        "last_name": "Okafor",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English", "Igbo"],
        "phone": "(312) 555-1046",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG009"],
        "facility_ids": ["FAC017"],
        "address": {
            "street": "2640 S King Dr",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8445,
            "longitude": -87.6170,
        },
    },
    {
        "npi": "1200000047",
        "first_name": "Linda",
        "last_name": "Chang",
        "prefix": "Dr.",
        "credentials": "MD, FACC",
        "specialty": "Cardiology",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Mandarin"],
        "phone": "(312) 555-1047",
        "accepting_new_patients": True,
        "telehealth_available": False,
        "organization_ids": ["ORG009"],
        "facility_ids": ["FAC016"],
        "address": {
            "street": "2525 S Michigan Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8462,
            "longitude": -87.6228,
        },
    },
    {
        "npi": "1200000048",
        "first_name": "Jorge",
        "last_name": "Ramirez",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Emergency Medicine",
        "subspecialties": [],
        "gender": "Male",
        "languages": ["English", "Spanish"],
        "phone": "(312) 555-1048",
        "accepting_new_patients": False,
        "telehealth_available": False,
        "organization_ids": ["ORG009"],
        "facility_ids": ["FAC016"],
        "address": {
            "street": "2525 S Michigan Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60616",
            "latitude": 41.8462,
            "longitude": -87.6228,
        },
    },
    # --- Chicago metro: Additional Logan Square area practitioners ---
    {
        "npi": "1200000049",
        "first_name": "Eva",
        "last_name": "Nowak",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Family Medicine",
        "subspecialties": [],
        "gender": "Female",
        "languages": ["English", "Polish", "Spanish"],
        "phone": "(773) 555-1049",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG011"],
        "facility_ids": ["FAC022"],
        "address": {
            "street": "3059 W Diversey Ave",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9322,
            "longitude": -87.7052,
        },
    },
    {
        "npi": "1200000050",
        "first_name": "Kenji",
        "last_name": "Watanabe",
        "prefix": "Dr.",
        "credentials": "MD",
        "specialty": "Psychiatry",
        "subspecialties": ["Addiction Psychiatry"],
        "gender": "Male",
        "languages": ["English", "Japanese"],
        "phone": "(773) 555-1050",
        "accepting_new_patients": True,
        "telehealth_available": True,
        "organization_ids": ["ORG010"],
        "facility_ids": ["FAC021"],
        "address": {
            "street": "2553 N Kedzie Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60647",
            "latitude": 41.9270,
            "longitude": -87.7076,
        },
    },
]
